feat: support for branches and content-types pagination.
Contentstack-Solutions/contentstack-cli-tsgen pull request #33
Opened 2023-05-24 10:37 UTC by vkalta

This PR resolves CS-38229.

2023-05-30 09:58 UTC, netrajpatel requested changes

2023-05-30 09:58 UTC, netrajpatel commented on src/commands/tsgen.ts
> +      char: 'b',
@vkalta Remove this short flag, current cli does not have any short flag for a branch flag.

2023-05-30 09:58 UTC, netrajpatel commented on src/commands/tsgen.ts
> +      required: true,
@vkalta Can you make this branch flag optional? We have some customers who do not have branches enabled yet.

2023-05-30 09:58 UTC, netrajpatel commented on src/lib/stack/client.ts
> +      branch: config.branch,
@vkalta This branch param should be optional

2023-06-26 08:10 UTC, netrajpatel commented on src/commands/tsgen.ts
> +      char: 'b',
@vkalta Can you please check this?

2023-06-26 08:43 UTC, aman19K commented
Hey @vkalta , Can you pls update the version ? version": "2.1.2 already released.
https://github.com/Contentstack-Solutions/contentstack-cli-tsgen/blob/master/package.json

cc: @netrajpatel

2023-07-03 06:16 UTC, aravindbuilt approved these changes

2023-07-03 06:16 UTC, netrajpatel approved these changes

2023-07-03 06:17 UTC, merged